id: I6424827C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T10:50:11+00:00'
last_modified: '2022-06-08T10:02:26.640764+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29260
  title: ཆོས་ཀྱི་འཁོར་ལོ་ལེགས་པར་གཏན་ལ་ཕབ་པ་ཐེག་པ་ཆེན་པོའི་ཚུལ་འོང་གེས་ཞུས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    40CC:
      image_group_id: I5536
      title: ''
      total_pages: 408
      order: 1
      base_file: 40CC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
